import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  console.log('=== Test resume-optimize with the ACTUAL production prompt ===')
  const { chatComplete } = await import('/home/z/my-project/src/lib/multi-ai.ts')
  
  const realResume = `John Doe
Software Engineer with 5+ years experience
Email: john@example.com

PROFESSIONAL SUMMARY
Results-driven Software Engineer with 5+ years of experience designing and building scalable web applications.

EXPERIENCE
Senior Software Engineer at Google (2022-Present)
- Led development of microservices-based payment processing system
- Built real-time analytics dashboard using React, Node.js, AWS Lambda

Software Engineer at Microsoft (2020-2022)
- Developed RESTful APIs using Python (Django) and Node.js (Express)
- Built responsive frontends with React, TypeScript, Tailwind CSS

EDUCATION
B.Tech in Computer Science, IIT Delhi (2015-2019)

SKILLS
Python, JavaScript, TypeScript, React, Node.js, AWS, Docker`

  const realJD = `Software Engineer at Google
Location: Bangalore, India

Requirements:
- 3+ years of experience in software development
- Strong proficiency in Python or Java
- Experience with distributed systems
- Knowledge of AWS

Preferred:
- Experience with Kubernetes and Docker
- Knowledge of PostgreSQL
- Understanding of CI/CD pipelines`

  const start = Date.now()
  try {
    const result = await chatComplete([
      {
        role: 'system',
        content: `You are an expert ATS resume optimizer and professional resume writer. Given a candidate's current resume and a target job description, produce a tailored, ATS-friendly resume that:

FORMATTING RULES (CRITICAL):
1. Start with the person's name as a # H1 heading (first line of output)
2. Below the name, add a single line with their contact info (email, phone, LinkedIn, location) — extracted from the original resume
3. Then add sections in this order:
   ## Professional Summary
   ## Core Skills
   ## Professional Experience
   ## Education
   ## Certifications (only if present in original resume)

CONTENT RULES:
4. Align keywords with the job description — mirror the exact terminology used in the JD
5. Quantify achievements wherever possible (use numbers, percentages, dollar amounts)
6. Reorder and rephrase bullet points to surface the most relevant experience first
7. Use strong action verbs (Led, Architected, Spearheaded, Optimized, etc.)
8. Each experience entry should have: Job Title | Company | Dates (format: Mon YYYY – Mon YYYY)
9. Keep the same factual content — do NOT invent new jobs, degrees, or employers
10. If the original resume has gaps or missing info, keep it as-is — don't fill in

OUTPUT RULES:
11. Output clean Markdown ONLY — no HTML, no LaTeX
12. Do NOT include a "Tailoring Notes" section — output should be a clean resume only
13. Do NOT include any metadata, dates, timestamps, or "Generated by" text
14. Do NOT include any URLs or hyperlinks — plain text only
15. The resume should be ready to print/download as-is — no extra commentary
16. Keep it to 1-2 pages max — be concise, not verbose
17. Use bullet points (not paragraphs) for experience entries
18. Each bullet should be 1-2 lines max — no walls of text`,
      },
      {
        role: 'user',
        content: `MY CURRENT RESUME:\n${realResume}\n\n---\n\nTARGET JOB DESCRIPTION:\n${realJD}\n\n---\n\nPlease produce the tailored ATS-optimized resume in Markdown. Output ONLY the resume — no tailoring notes, no explanations, no metadata.`,
      },
    ])
    
    console.log('  Time taken:', Date.now() - start, 'ms')
    console.log('  Response length:', result?.length || 0)
    
    if (!result || result.length < 100) {
      console.log('  ❌ Response too short or empty!')
      console.log('  Full response:', JSON.stringify(result))
    } else {
      console.log('  ✅ Response looks good')
      console.log('  First 400 chars:')
      console.log('  ' + result.slice(0, 400))
    }
  } catch (e: any) {
    console.log('  ❌ AI call FAILED in', Date.now() - start, 'ms')
    console.log('  Error:', e.message)
  }
}
main().catch(console.error).finally(() => prisma.$disconnect())
