import { NextRequest, NextResponse } from 'next/server'
import { chatComplete } from '@/lib/multi-ai'
import { getCurrentUser } from '@/lib/auth-server'
import { canUseAIToolWithAdGate as canUseAITool, incrementUsage } from '@/lib/subscription'
import { applyRateLimit } from '@/lib/apply-rate-limit'
import { recordAiUse } from '@/lib/rate-limit'
import { isValidTemplate, getTemplate } from '@/lib/resume-templates'

// POST /api/ai/resume-optimize
// Body: { resume: string, jobDescription: string, template?: string }
// Returns tailored, ATS-friendly resume formatted in the selected template's style.
//
// The `template` parameter is optional. When provided:
//   - Must be a valid template slug (validated against RESUME_TEMPLATES)
//   - AI prompt is modified with template-specific formatting instructions
//   - Response includes the template slug so the frontend knows which renderer to use
//
// When NOT provided, falls back to the original behavior (no template styling).
export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { resume, jobDescription, template: templateSlug } = body
    if (!resume || !jobDescription) {
      return NextResponse.json({ error: 'Both resume and jobDescription are required' }, { status: 400 })
    }

    // Validate template slug if provided
    if (templateSlug && !isValidTemplate(templateSlug)) {
      return NextResponse.json({ error: 'Invalid template' }, { status: 400 })
    }

    // Paywall: check user is authenticated + has remaining usage (or valid ad token)
    const user = await getCurrentUser(req)
    const adToken = new URL(req.url).searchParams.get('adToken')
    const usage = await canUseAITool('resumeOptimizations', user, adToken, req)
    if (!usage.allowed) {
      return NextResponse.json(
        {
          error: usage.message,
          requiresUpgrade: !usage.isPro && !usage.requiresAd,
          requiresAd: usage.requiresAd,
          used: usage.used,
          limit: usage.limit,
        },
        { status: 403 },
      )
    }

    // Template feature is Pro-only — UNLESS the template is marked as free
    const template = templateSlug ? getTemplate(templateSlug) : null
    if (templateSlug && !usage.isPro && template && !template.isFree) {
      return NextResponse.json(
        {
          error: 'This resume template is a Pro feature. Upgrade to Pro to use it, or pick a Free template.',
          requiresUpgrade: true,
          requiresPro: true,
        },
        { status: 403 },
      )
    }

    // Rate limit: 10/hour free, 30/hour pro
    const rateLimitResponse = applyRateLimit(user, 'resumeOptimizations')
    if (rateLimitResponse) return rateLimitResponse

    // Build the system prompt — base prompt + template-specific modifier
    // (template variable was already declared above for the Pro check)
    // const template = templateSlug ? getTemplate(templateSlug) : null

    // Build section list for the AI prompt
    const sectionList = template
      ? template.sections
          .filter((s) => s.id !== 'header')  // header is the name+contact, handled separately
          .map((s) => `- ${s.heading}${s.required ? ' (REQUIRED)' : ' (optional — skip if not in resume)'}${s.placeholder ? `. If not in resume: ${s.placeholder}` : ''}`)
          .join('\n')
      : `## Professional Summary
## Core Skills
## Professional Experience
## Education
## Certifications (only if present in original resume)`

    const templateModifier = template?.aiPromptModifier || ''

    const systemPrompt = `You are an expert ATS resume optimizer and professional resume writer. Given a candidate's current resume and a target job description, produce a tailored, ATS-friendly resume that:

FORMATTING RULES (CRITICAL):
1. Start with the person's name as a # H1 heading (first line of output)
2. Below the name, add a single line with their contact info (email, phone, LinkedIn, location) — extracted from the original resume
3. Then add ONLY the sections specified below (don't add extra sections)

SECTIONS TO INCLUDE${template ? ` (for ${template.name} template)` : ''}:
${sectionList}

CONTENT RULES:
4. Align keywords with the job description — mirror the exact terminology used in the JD
5. Quantify achievements wherever possible (use numbers, percentages, dollar amounts)
6. Use strong action verbs (Led, Architected, Spearheaded, Optimized, etc.)
7. Keep the same factual content — do NOT invent new jobs, degrees, or employers
8. If the original resume has gaps or missing info, keep it as-is — don't fill in

OUTPUT RULES:
9. Output clean Markdown ONLY — no HTML, no LaTeX
10. Do NOT include a "Tailoring Notes" section — output should be a clean resume only
11. Do NOT include any metadata, dates, timestamps, or "Generated by" text
12. Do NOT include any URLs or hyperlinks — plain text only
13. CRITICAL: FILL exactly 1 FULL PAGE. The resume should fill an entire A4 page — not be half-empty. Include ALL relevant experience, skills, and sections. Use 5-6 bullets per job (not 4). Include 2-3 sentences for the summary. Add detail to each bullet point (quantify with numbers, mention technologies used, describe impact). Do NOT skip experience unless it's from more than 10 years ago.
14. Use bullet points (not paragraphs) for experience entries
15. Each bullet should be 1-2 lines — include specific details, metrics, and technologies

PLACEHOLDER RULES:
- For optional sections where the user's resume has NO data:
  - If a placeholder is specified above, output EXACTLY that placeholder text (e.g. "[Add your certifications]")
  - This tells the user they need to fill in that section
- For required sections where the user's resume has NO data:
  - Use sensible default/example content based on the job description
  - E.g. for "Core Competencies" use keywords from the JD
  - E.g. for "Professional Summary" write a 2-sentence summary based on the JD + user's skills${template ? `

TEMPLATE-SPECIFIC FORMATTING (selected template: ${template.name}):
${templateModifier}` : ''}`

    const raw = await chatComplete([
      {
        role: 'system',
        content: systemPrompt,
      },
      {
        role: 'user',
        content: `MY CURRENT RESUME:\n${resume}\n\n---\n\nTARGET JOB DESCRIPTION:\n${jobDescription}\n\n---\n\nPlease produce the tailored ATS-optimized resume in Markdown. Output ONLY the resume — no tailoring notes, no explanations, no metadata.`,
      },
    ])

    let content = raw || ''

    // Clean up the AI output:
    // 1. Remove "Tailoring Notes" section (AI sometimes adds it despite instructions)
    // 2. Remove markdown links [text](url) → keep just the text
    // 3. Remove any "Generated by" or timestamp lines
    content = content
      // Remove Tailoring Notes section (## Tailoring Notes until end or next ## heading)
      .replace(/^##\s*Tailoring Notes[\s\S]*?(?=\n##\s|\n#\s|$)/gim, '')
      .replace(/^Tailoring Notes[\s\S]*?(?=\n##\s|\n#\s|$)/gim, '')
      // Remove "Generated by Hirebase" or similar
      .replace(/Generated by.*$/gim, '')
      .replace(/---\s*Generated.*$/gim, '')
      // Remove markdown links — keep text only, remove URL
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      // Remove any remaining URLs
      .replace(/https?:\/\/[^\s)]+/g, '')
      // Trim extra whitespace
      .trim()

    // Increment usage counter AFTER successful AI call
    // Skip if user watched an ad (ad-watched = free use, doesn't consume quota)
    if (!usage.adWatched && user?.id) {
      await incrementUsage('resumeOptimizations', user.id)
      recordAiUse(user?.id || 'anonymous', 'resumeOptimizations')
    }

    return NextResponse.json({
      result: content,
      template: templateSlug || null,
      templateName: template?.name || null,
      usage: {
        used: usage.used + 1,
        limit: usage.limit,
        remaining: Math.max(0, usage.limit - usage.used - 1),
        isPro: usage.isPro,
      },
    })
  } catch (e: any) {
    console.error('AI resume optimize error:', e)
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
