import { NextRequest, NextResponse } from 'next/server'
import { chatComplete } from '@/lib/multi-ai'
import { getCurrentUser } from '@/lib/auth-server'
import { canUseAIToolWithAdGate as canUseAITool, incrementUsage } from '@/lib/subscription'

// POST /api/ai/resume-optimize
// Body: { resume: string, jobDescription: string }
// Returns tailored, ATS-friendly resume
export async function POST(req: NextRequest) {
  try {
    const { resume, jobDescription } = await req.json()
    if (!resume || !jobDescription) {
      return NextResponse.json({ error: 'Both resume and jobDescription are required' }, { status: 400 })
    }

    // Paywall: check user is authenticated + has remaining usage (or valid ad token)
    const user = await getCurrentUser(req)
    const adToken = new URL(req.url).searchParams.get('adToken')
    const usage = await canUseAITool('resumeOptimizations', user, adToken, req)
    if (!usage.allowed) {
      return NextResponse.json(
        {
          error: usage.message,
          requiresUpgrade: !usage.isPro && !usage.requiresAd,
          requiresAd: usage.requiresAd,
          used: usage.used,
          limit: usage.limit,
        },
        { status: 403 },
      )
    }

    const raw = await chatComplete(
      [
        {
          role: 'system',
          content: `You are an expert ATS resume optimizer and professional resume writer. Given a candidate's current resume and a target job description, produce a tailored, ATS-friendly resume that:

FORMATTING RULES (CRITICAL):
1. Start with the person's name as a # H1 heading (first line of output)
2. Below the name, add a single line with their contact info (email, phone, LinkedIn, location) — extracted from the original resume
3. Then add sections in this order:
   ## Professional Summary
   ## Core Skills
   ## Professional Experience
   ## Education
   ## Certifications (only if present in original resume)

CONTENT RULES:
4. Align keywords with the job description — mirror the exact terminology used in the JD
5. Quantify achievements wherever possible (use numbers, percentages, dollar amounts)
6. Reorder and rephrase bullet points to surface the most relevant experience first
7. Use strong action verbs (Led, Architected, Spearheaded, Optimized, etc.)
8. Each experience entry should have: Job Title | Company | Dates (format: Mon YYYY – Mon YYYY)
9. Keep the same factual content — do NOT invent new jobs, degrees, or employers
10. If the original resume has gaps or missing info, keep it as-is — don't fill in

OUTPUT RULES:
11. Output clean Markdown ONLY — no HTML, no LaTeX
12. Do NOT include a "Tailoring Notes" section — output should be a clean resume only
13. Do NOT include any metadata, dates, timestamps, or "Generated by" text
14. Do NOT include any URLs or hyperlinks — plain text only
15. The resume should be ready to print/download as-is — no extra commentary
16. Keep it to 1-2 pages max — be concise, not verbose
17. Use bullet points (not paragraphs) for experience entries
18. Each bullet should be 1-2 lines max — no walls of text`,
        },
        {
          role: 'user',
          content: `MY CURRENT RESUME:\n${resume}\n\n---\n\nTARGET JOB DESCRIPTION:\n${jobDescription}\n\n---\n\nPlease produce the tailored ATS-optimized resume in Markdown. Output ONLY the resume — no tailoring notes, no explanations, no metadata.`,
        },
      ])

    let content = raw || ''

    // Clean up the AI output:
    // 1. Remove "Tailoring Notes" section (AI sometimes adds it despite instructions)
    // 2. Remove markdown links [text](url) → keep just the text
    // 3. Remove any "Generated by" or timestamp lines
    content = content
      // Remove Tailoring Notes section (## Tailoring Notes until end or next ## heading)
      .replace(/^##\s*Tailoring Notes[\s\S]*?(?=\n##\s|\n#\s|$)/gim, '')
      .replace(/^Tailoring Notes[\s\S]*?(?=\n##\s|\n#\s|$)/gim, '')
      // Remove "Generated by Hirebase" or similar
      .replace(/Generated by.*$/gim, '')
      .replace(/---\s*Generated.*$/gim, '')
      // Remove markdown links — keep text only, remove URL
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      // Remove any remaining URLs
      .replace(/https?:\/\/[^\s)]+/g, '')
      // Trim extra whitespace
      .trim()

    // Increment usage counter AFTER successful AI call
    // Skip if user watched an ad (ad-watched = free use, doesn't consume quota)
    if (!usage.adWatched && user?.id) {
      await incrementUsage('resumeOptimizations', user.id)
    }

    return NextResponse.json({
      result: content,
      usage: {
        used: usage.used + 1,
        limit: usage.limit,
        remaining: Math.max(0, usage.limit - usage.used - 1),
        isPro: usage.isPro,
      },
    })
  } catch (e: any) {
    console.error('AI resume optimize error:', e)
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
